services:
  plotter:
    build:
      context: .
      dockerfile: Dockerfile.plotter
    image: plotter:latest
    working_dir: /code
    volumes:
      - .:/code
    container_name: plotter
    tty: true